services:
   appProxy:
    build: ./data
    restart: unless-stopped
    container_name: appProxy
    volumes:
        - ./data/default.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - "80:80"
    networks:
      - mcnet